_prefs: 
  baselayer: ''
  mapid: thethirdpole.31faf541
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 86.0449
  - 29.4587
  - 4
description: ''
format: "png8:m=h:c=128"
interactivity_layer: ''
layers: 
  - landcover
  - landuse
  - hillshade
  - contour.line
  - waterway
  - water
  - thethirdpole_water_bodies
  - perennial_river
  - aeroway
  - barrier_line
  - building
  - landuse_overlay
  - tunnel
  - road
  - thethirdpole_roads
  - bridge
  - admin
  - country_label_line
  - country_label
  - marine_label
  - state_label
  - place_label
  - water_label
  - poi_label
  - road_label
  - waterway_label
  - contour.label
maxzoom: 8
minzoom: 2
name: Basemap - Hindu-Kush Himalaya
source: "mapbox:///mapbox.mapbox-terrain-v1,thethirdpole.water_bodies,thethirdpole.5bd99a4a,mapbox.mapbox-streets-v5,thethirdpole.roads"
styles: 
  - vars.mss
  - bg.mss
  - labels.mss
  - roads.mss
  - pois.mss
  - thirdpole.mss
template: ''
